### ISSUE TITLE
Is it possible in http?

### ISSUE THREAD

**Issue by Nuwanda22** [wlzla000/DodgeChrome-plus-plus#2]
like http://fuq.com

**Comment by wlzla000** [comment]
Do you mean `Is it possible to bypass Warning.or.kr on HTTP protocol with DodgeChrome++?`?
Yes, and **that's what _DodgeChrome++_ is for.**

Since all the HTTPS requests are encrypted so that they're not blocked, _DodgeChrome++_ intervenes **only in HTTP requests**; as you can see here:
  - https://github.com/wlzla000/DodgeChrome-plus-plus/blob/e1f9bdaca156eb2026a797456d2058c14606b4cb/source/manifest.json#L17-L22
  - https://github.com/wlzla000/DodgeChrome-plus-plus/blob/e1f9bdaca156eb2026a797456d2058c14606b4cb/source/DodgeChrome++.js#L66-L68
