### ISSUE TITLE
Add service page

### ISSUE THREAD

**Issue by Nuwanda22** [wlzla000/DodgeChrome-plus-plus#3]
![image](https://user-images.githubusercontent.com/16515307/29600462-fc1b3d24-8810-11e7-917f-c88622aedc78.png)

Like this page

I wanna on/off

**Comment by wlzla000** [comment]
What you said was already implemented.

I will add some more options here, however it is possible to activate and deactivate _DodgeChrome++_ since the initial release/commit; i.e. currently:
https://github.com/wlzla000/DodgeChrome-plus-plus/blob/1e069609e74e224c9780128fcc6e3b76226d8b0c/source/DodgeChrome++-settings.html#L1-L17

I close this issue, but please don't hesitate to re-open this issue if this answer is not what you meant.
